### ISSUE TITLE
Can I view "attachments" properties on SlackLogViewer?

### ISSUE THREAD

**Issue by kumarin3** [thayakawa-gh/SlackLogViewer#11]
The quotes in the Slack logs seem to be stored in the "attachments" property in the JSON file, is there any way to display this?

**Comment by thayakawa-gh** [comment]
Hi, @kumarin3.
Quotes cannot be displayed in the current version of SlackLogViewer. I'll consider adding that function in the next version.

**Comment by kumarin3** [comment]
Thank you for your reply.
I would be very helpful if you could implement it.
I am very grateful to you for creating this viewer.

**Comment by thayakawa-gh** [comment]
Sorry for the delay in my reply. It has been implemented in v1.2.Alpha-1.

**Comment by kumarin3** [comment]
Thank you for extending the functionality of the SlackLogViewer.
I will be very grateful to use it.
