### ISSUE TITLE
Font color goes white and cannot read on Mac's dark mode

### ISSUE THREAD

**Issue by welchensen** [thayakawa-gh/SlackLogViewer#12]
It's probably because the app uses the system's default setting for the font color, so all texts are white on the white background and can't read anything.
Maybe have the font stick to black no matter what theme - light or dark - the system uses?

**Comment by peterjmorgan** [comment]
@thayakawa-gh I tested this branch and it works great on my mac (13.1 m1 max with dark system color)

**Comment by thayakawa-gh** [comment]
Thank you for testing, @peterjmorgan.
I will merge the fix into the next release.

**Comment by thayakawa-gh** [comment]
Merged into the master branch.
