### ISSUE TITLE
linux path separators are broken

### ISSUE THREAD

**Issue by G-Harmon** [thayakawa-gh/SlackLogViewer#14]
Trying to use this on linux, looks like the path separators are hard-coded to Windows style, `\`.
To get this to work, I had to change the "\\" in GlobalVariables.cpp to be `/`.

**Comment by thayakawa-gh** [comment]
Thank you for your bug report. This bug appears when a folder of export files is opened, but now I have confirmed that it can be opened and is displayed correctly.
