### ISSUE TITLE
SlackLogViewer does not displays images and files (Win)

### ISSUE THREAD

**Issue by herianp** [thayakawa-gh/SlackLogViewer#23]
Hi, i have a problem with images and files. I created export (zip file) throught slackdump, but images are not showing.
![slacklog](https://github.com/user-attachments/assets/89f7ac3b-3e61-4044-9032-859a60c1d0aa)
Cache status knows about the images..

Any idea what is wrong?
![image](https://github.com/user-attachments/assets/9853dd83-1a26-4e17-9a02-dc9f30b8a8f8)

**Comment by MarcinKukulka** [comment]
I have the same problem

**Comment by thayakawa-gh** [comment]
Please see #18.
