### ISSUE TITLE
Cannot make cache folder

### ISSUE THREAD

**Issue by rusq** [thayakawa-gh/SlackLogViewer#5]
Hi there, just read about this tool on [note.com](https://note.com/wildriver/n/ne0f7969a9c3b), it looks great, I was eager to try it out, but getting this error on macOS 15.2 monterey: "cannot make cache folder"

Steps to reproduce:
1. Open SlackLogViewer
2. From top left menu, choose "Open ZIP"
3. Select file
4. Error appears:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/16064414/187025187-926ddc7c-f1af-45de-a799-15d0ac650a82.png">

Expected behaviour:
4. File is loaded.

I read [this article](https://kenkyu-note.hatenablog.com/entry/2022/08/10/231039) (with google translate), and understand that there's some difficulty for testing and debugging on macOS, but thought I'd create an issue to flag this.

Thank you :)

**Comment by thayakawa-gh** [comment]
Thank you for using my application.
Are you using the binary distributed for macOS? Or did you build it yourself? If the former, there may be some problems with the binary.
This error message appears when this app can not make some directories for storing temporary files under the "Cache" directory, which should exist under the current directory. On windows, for example, the directory structure is as follows:
```
SlackLogViewer/
    Cache/
    Resources/
    SlackLogViewer.exe
    ...
```
If there is no such directory in the current directory, I think we failed to create the directory in the binary.
Could you please create "Cache" directory manually and try again?

**Comment by cielavenir** [comment]
or please use https://github.com/thayakawa-gh/SlackLogViewer/pull/4#issuecomment-1229202030 binary

**Comment by rusq** [comment]
I was using the Release build "SlackLogViewer.v1.1.Beta-4.1-macos.tar.xz", will try the approach in the comment, thank you @thayakawa-gh @cielavenir !  Will let you know how it goes

**Comment by rusq** [comment]
Thank you! I used the binary linked by @cielavenir , it still did not work, but then I took it apart and recreated in the following way:
```
$ tree -L 2 .
.
|-- Frameworks
|   |-- QtConcurrent.framework
|   |   |-- QtConcurrent -> Versions/Current/QtConcurrent
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtCore.framework
|   |   |-- QtCore -> Versions/Current/QtCore
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtDBus.framework
|   |   |-- QtDBus -> Versions/Current/QtDBus
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtGui.framework
|   |   |-- QtGui -> Versions/Current/QtGui
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtNetwork.framework
|   |   |-- QtNetwork -> Versions/Current/QtNetwork
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtPdf.framework
|   |   |-- QtPdf -> Versions/Current/QtPdf
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtPositioning.framework
|   |   |-- QtPositioning -> Versions/Current/QtPositioning
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtPrintSupport.framework
|   |   |-- QtPrintSupport -> Versions/Current/QtPrintSupport
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtQml.framework
|   |   |-- QtQml -> Versions/Current/QtQml
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtQmlModels.framework
|   |   |-- QtQmlModels -> Versions/Current/QtQmlModels
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtQuick.framework
|   |   |-- QtQuick -> Versions/Current/QtQuick
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtQuickWidgets.framework
|   |   |-- QtQuickWidgets -> Versions/Current/QtQuickWidgets
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtSerialPort.framework
|   |   |-- QtSerialPort -> Versions/Current/QtSerialPort
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtSvg.framework
|   |   |-- QtSvg -> Versions/Current/QtSvg
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtVirtualKeyboard.framework
|   |   |-- QtVirtualKeyboard -> Versions/Current/QtVirtualKeyboard
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtWebChannel.framework
|   |   |-- QtWebChannel -> Versions/Current/QtWebChannel
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtWebEngineCore.framework
|   |   |-- Helpers -> Versions/Current/Helpers
|   |   |-- QtWebEngineCore -> Versions/Current/QtWebEngineCore
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtWebEngineWidgets.framework
|   |   |-- QtWebEngineWidgets -> Versions/Current/QtWebEngineWidgets
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- QtWidgets.framework
|   |   |-- QtWidgets -> Versions/Current/QtWidgets
|   |   |-- Resources -> Versions/Current/Resources
|   |   `-- Versions
|   |-- libquazip1-qt5.1.0.0.dylib
|   `-- libtbb.12.dylib
|-- Info.plist
|-- MacOS
|   |-- Cache
|   |-- Resources
|   |   |-- batsu.png
|   |   |-- cache.svg
|   |   |-- calendar.svg
|   |   |-- clear.svg
|   |   |-- document.png
|   |   |-- download.png
|   |   |-- download.svg
|   |   |-- downloading.png
|   |   |-- menu.png
|   |   |-- qt.conf
|   |   |-- regex.png
|   |   |-- search.png
|   |   `-- upper_lower_case.png
|   |-- SlackLogViewer
|   `-- settings.ini
`-- PlugIns
    |-- bearer
    |   `-- libqgenericbearer.dylib
    |-- iconengines
    |   `-- libqsvgicon.dylib
    |-- imageformats
    |   |-- libqgif.dylib
    |   |-- libqicns.dylib
    |   |-- libqico.dylib
    |   |-- libqjpeg.dylib
    |   |-- libqmacheif.dylib
    |   |-- libqmacjp2.dylib
    |   |-- libqpdf.dylib
    |   |-- libqtga.dylib
    |   |-- libqtiff.dylib
    |   |-- libqwbmp.dylib
    |   `-- libqwebp.dylib
    |-- platforminputcontexts
    |   `-- libqtvirtualkeyboardplugin.dylib
    |-- platforms
    |   `-- libqcocoa.dylib
    |-- position
    |   |-- libqtposition_cl.dylib
    |   |-- libqtposition_positionpoll.dylib
    |   `-- libqtposition_serialnmea.dylib
    |-- printsupport
    |   `-- libcocoaprintersupport.dylib
    |-- styles
    |   `-- libqmacstyle.dylib
    `-- virtualkeyboard
        |-- libqtvirtualkeyboard_hangul.dylib
        |-- libqtvirtualkeyboard_openwnn.dylib
        |-- libqtvirtualkeyboard_pinyin.dylib
        |-- libqtvirtualkeyboard_tcime.dylib
        `-- libqtvirtualkeyboard_thai.dylib

72 directories, 62 files

```

And it worked.  Seems that the Cache and Resource folders need to be place alongside of the "SlackLogViewer" inside the `MacOS` directory within the "SlackLogViewer.app" .

Having created this folder structure, my observations were the following:
1. If I run `MacOS/SlackLogViewer` executable directly, I can see the menu image and open the test archive with no problem - (btw it works very fast)!
2. If I run the `SlackLogViewer.app` from the Finder, the issue with "cannot make cache folder" and menu is not visible.

**Comment by cielavenir** [comment]
@rusq It seems extracting by Unarchiver is subject to quarantine (gatekeeper) and it causes weird cwd.

as shown in this movie, please extract by Archive Utility (or terminal "tar xf").

https://user-images.githubusercontent.com/1495368/187059546-d3542fa5-91a5-4f03-836e-8e60d75764ee.mp4

**Comment by cielavenir** [comment]
oh, need to run `xattr -d com.apple.quarantine SlackLogViewer_macos.tar.xz` before running Archive Utility...

**Comment by rusq** [comment]
Hi @cielavenir, thanks for the update, and sharing the video: 

I tried it with the same result - recorded a video too: https://mega.nz/file/uzBSgRob#_WyX874j5dglxwODDm_VXTCUpKK7Yo7ZlQs8n4LG-bk (325.8 MB)

I did reset xattr, but I also used `tar -xf` (as seen on the video).  I also shown how I did make it work.

The reason I'm looking at this project, as I'm thinking of listing it as an option to view Slack files in the github.com/rusq/slackdump project, before this, I'm trying to test it myself, to understand how easy is it to use.  I personally really like it - it works much faster than `slack-export-viewer`.

**Comment by thayakawa-gh** [comment]
@rusq Perhaps I have to fix the codes accessing to caches and resources. I have been looking into the behavior of macOS and application bundle for a while, and it seems that these files cannot be accessed correctly in the same way as windows or linux. As you know, this application was just made for windows, not for macOS.

I was just testing to make it read the zip file that slackdump outputs (and found some problems). I will publish a new release including the fixes above in the near future.

**Comment by cielavenir** [comment]
ah... thank you for the video, according to it your "current directory" is clearly `/Volumes/Data`. Somehow in my macbook the "current directory" is set to the same directory as .app.

I get sometimes confused as I'm not sure about GUI apps current directory on both macOS and Win and I don't know how to fix it...

Anyway with https://github.com/thayakawa-gh/SlackLogViewer/pull/8 , Cache and Resources are moved to SlackLogViewer.app/Content/MacOS and the "current directory" is forced there, and the issue should be gone.

Please check the "macos" binary in https://github.com/cielavenir/SlackLogViewer/actions/runs/2949398984

(As a "bonus", this SlackLogViewer.app can be put to /Applications)

**Comment by thayakawa-gh** [comment]
I think that using the absolute paths to Cache and Resources are more preferable than changing current directory in the application. It is possible that for some reason, for example, when users want to output some files to the working directory, the current directory becomes unchangeable. And, in the Qt app, there is an easy way to get the path.

By the way, is "MacOS" directory suitable for the location of the resources and temporary files? Some articles seems to suggest that such files should be placed in "Resources" directory.

**Comment by cielavenir** [comment]
@thayakawa-gh actually SlackLogViewer.app/Contents/Resources/ and $HOME/Caches/SlackLogViewer are better dirs.

The thing is SlackLogViewer's entire directory access has to be rewritten.

**Comment by rusq** [comment]
Thanks for looking into this.

Probably, for cache dir, it would be possible to adopt the same logic used by `os.UserCacheDir()` function in golang?  https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/os/file.go;l=405
I don't have much experience developing GUI apps for MacOS either, and I'm not sure if this would be accessible by the "App".

Or, probably, $TEMP could be considered?

**Comment by cielavenir** [comment]
> entire directory access has to be rewritten.

@thayakawa-gh to be clear, I mean there are so many hardcoded Cache/ and Resource/. Could you put these string into a function? (otherwise I still feel chdir is quickest workaround)

**Comment by thayakawa-gh** [comment]
Please check the [test branch](/thayakawa-gh/SlackLogViewer/tree/change_cache_and_resources_location). All hard-coded paths have been rewritten, and the paths to Cache and Resources are defined in lines 13-29 of [main.cpp](https://github.com/thayakawa-gh/SlackLogViewer/blob/8f854fe1a29b47c38d71835bdfd3144f0df2933d/SlackLogViewer/main.cpp). I'm not sure whether QDir::temp() (returns `$TMPDIR` or `/tmp`) or `$HOME/Cache` is more suitable.
It was not much effort compared to the difficulty of creating a new feature. In addition, it was a good opportunity to rewrite foolish hard-coded paths.

The binary for macOS is [here](https://github.com/thayakawa-gh/SlackLogViewer/actions/runs/2953635035) (thanks to @cielavenir).

However, I have a hard time deciding where to store caches. I use the function of the cache as practially a backup of files (and recommend users to do so in [this article](https://kenkyu-note.hatenablog.com/entry/2020/09/28/045232)). If they are stored in the temporary dir, there is a possibility that users may unintentionally delete them. Should we allow users to choose where to store them? For example, place under the same directory as the Resources by default and make it rewritable in `setting.ini`.

**Comment by cielavenir** [comment]
@thayakawa-gh the binary does not work...

direct execution says this `QCoreApplication::applicationDirPath: Please instantiate the QApplication object first`

**Comment by thayakawa-gh** [comment]
@cielavenir Thank you for testing.
Hmm... Qt behavior on macOS seems to be a bit different from that on windows.
I have rearranged the order of the calls. Could you try [this binary](https://github.com/thayakawa-gh/SlackLogViewer/actions/runs/2958081153) again?

**Comment by cielavenir** [comment]
This one works

@rusq ok on your machine as well?

**Comment by rusq** [comment]
@cielavenir @thayakawa-gh It works, straight out of the archive!  Thank you for resolving this :)

<img width="844" alt="image" src="https://user-images.githubusercontent.com/16064414/187534773-67067d3b-dcd2-422f-ab31-3a040df11d1f.png">

**Comment by rusq** [comment]
I will have couple of more suggestions, if you don't mind, will describe in separate issues.

Thanks for resolving this so quickly - it's a great product and I personally think it's much better and more convenient to use then other viewers out there in both speed of operation and the code  quality.

There's a high interest in export viewers, because slack has introduced this silly 90-day policy on the free accounts, where any message older than 90 days is hidden, so people are exporting their workspaces.

I'll post a link to the SlackLogViewer in the slackdump repo.

**Comment by cielavenir** [comment]
@rusq that's nice

@thayakawa-gh thank you for the support

**Comment by thayakawa-gh** [comment]
@rusq I'm glad I could help you. @cielavenir Thank you for your investigation.
I will release the branch after a small fix (Qt::tmp() seems not to be a suitable location for the Cache dir. The logic in `os.UserCacheDir()` @rusq suggested may be a good solution).

Comments and Suggestions are always welcome, please feel free to contact me. However, I will be very busy for the next half year, so I don't know if I will be able to accommodate you right away...

**Comment by rusq** [comment]
> Comments and Suggestions are always welcome, please feel free to contact me. However, I will be very busy for the next half year, so I don't know if I will be able to accommodate you right away...

Thank you! Of course, I understand.  Open source projects are like collective farm - everyone is responsible for their own happiness 😂  Maybe I'll refresh my C++ knowledge and would be able to contribute at some point, I have QtCreator installed on my machine, but did not have any practical application for it.  Maybe that's the chance!

I mentioned this project, along with what I'm to suggest in the discussion that was started by one of the contributors to slackdump - maybe you could share some insights and suggestions too?https://github.com/rusq/slackdump/discussions/127

**Comment by thayakawa-gh** [comment]
@rusq I browsed the discussion and found it interesting. I will comment if I come up something.
