### ISSUE TITLE
Menu is not visible on macOS

### ISSUE THREAD

**Issue by rusq** [thayakawa-gh/SlackLogViewer#6]
macOS 15.2 monterey (amd64)

It's really hard to find the menu, if you don't know it's approximate location.

I assume it can't find the icon?

<img width="511" alt="image" src="https://user-images.githubusercontent.com/16064414/187025496-9bc8133c-33c2-45b3-8c14-e7beb91b4db3.png">

Thanks!

**Comment by thayakawa-gh** [comment]
It is related to #5, I think "Resources" directory containing icons may not exist in the current directory. Could you copy the directory to the current directory yourself? You can download the directory and icons from [here](https://github.com/thayakawa-gh/SlackLogViewer/tree/master/SlackLogViewer/Resources).

**Comment by cielavenir** [comment]
or please use https://github.com/thayakawa-gh/SlackLogViewer/pull/4#issuecomment-1229202030 binary

**Comment by rusq** [comment]
Resolved in #5
